version: '2'
services:
  corvina-node-device:
    image: corvina-node-device
    ports:
      - "18080:3000"
    extra_hosts:
      - "corvina.fog:10.10.10.225"
      - "app.corvina.fog:10.10.10.225"
      - "auth.corvina.fog:10.10.10.225"
      - "licenses.corvina.fog:10.10.10.225"
      - "pairing.corvina.fog:10.10.10.225"
      - "broker.corvina.fog:10.10.10.225"
      - "appengine.api.platform.corvina.fog:10.10.10.225"
      - "api.platform.corvina.fog:10.10.10.225"
    restart: always
